// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/types.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Block struct {
	Header               *Header        `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Transactions         []*Transaction `protobuf:"bytes,2,rep,name=transactions,proto3" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2f027f54ad4521e, []int{0}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Block) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type Header struct {
	Version              int32    `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Height               int32    `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	PreviousHash         []byte   `protobuf:"bytes,3,opt,name=previousHash,proto3" json:"previousHash,omitempty"`
	RootHash             []byte   `protobuf:"bytes,4,opt,name=rootHash,proto3" json:"rootHash,omitempty"`
	Timestamp            int64    `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2f027f54ad4521e, []int{1}
}

func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Header) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Header) GetPreviousHash() []byte {
	if m != nil {
		return m.PreviousHash
	}
	return nil
}

func (m *Header) GetRootHash() []byte {
	if m != nil {
		return m.RootHash
	}
	return nil
}

func (m *Header) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type TxInput struct {
	// The previous hash of the transaction containing
	// the output we want to spend
	PrevTxHash []byte `protobuf:"bytes,1,opt,name=prevTxHash,proto3" json:"prevTxHash,omitempty"`
	// The index of the output of the previous transaction we
	// want to spend
	PrevOutIndex         uint32   `protobuf:"varint,2,opt,name=prevOutIndex,proto3" json:"prevOutIndex,omitempty"`
	PublicKey            []byte   `protobuf:"bytes,3,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	Signature            []byte   `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxInput) Reset()         { *m = TxInput{} }
func (m *TxInput) String() string { return proto.CompactTextString(m) }
func (*TxInput) ProtoMessage()    {}
func (*TxInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2f027f54ad4521e, []int{2}
}

func (m *TxInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxInput.Unmarshal(m, b)
}
func (m *TxInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxInput.Marshal(b, m, deterministic)
}
func (m *TxInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxInput.Merge(m, src)
}
func (m *TxInput) XXX_Size() int {
	return xxx_messageInfo_TxInput.Size(m)
}
func (m *TxInput) XXX_DiscardUnknown() {
	xxx_messageInfo_TxInput.DiscardUnknown(m)
}

var xxx_messageInfo_TxInput proto.InternalMessageInfo

func (m *TxInput) GetPrevTxHash() []byte {
	if m != nil {
		return m.PrevTxHash
	}
	return nil
}

func (m *TxInput) GetPrevOutIndex() uint32 {
	if m != nil {
		return m.PrevOutIndex
	}
	return 0
}

func (m *TxInput) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *TxInput) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type TxOutput struct {
	Amount               int64    `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Address              []byte   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxOutput) Reset()         { *m = TxOutput{} }
func (m *TxOutput) String() string { return proto.CompactTextString(m) }
func (*TxOutput) ProtoMessage()    {}
func (*TxOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2f027f54ad4521e, []int{3}
}

func (m *TxOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxOutput.Unmarshal(m, b)
}
func (m *TxOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxOutput.Marshal(b, m, deterministic)
}
func (m *TxOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxOutput.Merge(m, src)
}
func (m *TxOutput) XXX_Size() int {
	return xxx_messageInfo_TxOutput.Size(m)
}
func (m *TxOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_TxOutput.DiscardUnknown(m)
}

var xxx_messageInfo_TxOutput proto.InternalMessageInfo

func (m *TxOutput) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *TxOutput) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

type Transaction struct {
	Version              int32    `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2f027f54ad4521e, []int{4}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func init() {
	proto.RegisterType((*Block)(nil), "Block")
	proto.RegisterType((*Header)(nil), "Header")
	proto.RegisterType((*TxInput)(nil), "TxInput")
	proto.RegisterType((*TxOutput)(nil), "TxOutput")
	proto.RegisterType((*Transaction)(nil), "Transaction")
}

func init() { proto.RegisterFile("proto/types.proto", fileDescriptor_e2f027f54ad4521e) }

var fileDescriptor_e2f027f54ad4521e = []byte{
	// 347 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xcd, 0x4e, 0x83, 0x40,
	0x14, 0x85, 0x43, 0xb1, 0xb4, 0xde, 0xe2, 0xc2, 0x59, 0x34, 0xc4, 0x18, 0x25, 0x6c, 0x64, 0x23,
	0x98, 0xba, 0x75, 0xd5, 0x55, 0x1b, 0x17, 0x4d, 0x26, 0xac, 0xba, 0x9b, 0xc2, 0x08, 0x13, 0xcb,
	0x0c, 0x99, 0x9f, 0x86, 0x3e, 0x82, 0x6f, 0xe0, 0xe3, 0x1a, 0x46, 0x2a, 0xed, 0xc2, 0x15, 0x9c,
	0xef, 0x90, 0x73, 0x4f, 0x2e, 0x17, 0x6e, 0x1b, 0x29, 0xb4, 0x48, 0xf5, 0xb1, 0xa1, 0x2a, 0xb1,
	0xef, 0xd1, 0x16, 0xc6, 0xcb, 0xbd, 0xc8, 0x3f, 0xd1, 0x23, 0x78, 0x15, 0x25, 0x05, 0x95, 0x81,
	0x13, 0x3a, 0xf1, 0x6c, 0x31, 0x49, 0x56, 0x56, 0xe2, 0x1e, 0xa3, 0x17, 0xf0, 0xb5, 0x24, 0x5c,
	0x91, 0x5c, 0x33, 0xc1, 0x55, 0x30, 0x0a, 0xdd, 0x78, 0xb6, 0xf0, 0x93, 0x6c, 0x80, 0xf8, 0xe2,
	0x8b, 0xe8, 0xdb, 0x01, 0xef, 0x37, 0x04, 0x05, 0x30, 0x39, 0x50, 0xa9, 0x98, 0xe0, 0x36, 0x7e,
	0x8c, 0x4f, 0x12, 0xcd, 0xbb, 0xb9, 0xac, 0xac, 0x74, 0x30, 0xb2, 0x46, 0xaf, 0x50, 0x04, 0x7e,
	0x23, 0xe9, 0x81, 0x09, 0xa3, 0x56, 0x44, 0x55, 0x81, 0x1b, 0x3a, 0xb1, 0x8f, 0x2f, 0x18, 0xba,
	0x83, 0xa9, 0x14, 0x42, 0x5b, 0xff, 0xca, 0xfa, 0x7f, 0x1a, 0xdd, 0xc3, 0xb5, 0x66, 0x35, 0x55,
	0x9a, 0xd4, 0x4d, 0x30, 0x0e, 0x9d, 0xd8, 0xc5, 0x03, 0x88, 0xbe, 0x1c, 0x98, 0x64, 0xed, 0x9a,
	0x37, 0x46, 0xa3, 0x07, 0x80, 0x2e, 0x35, 0x6b, 0x6d, 0x8e, 0x63, 0x73, 0xce, 0xc8, 0xa9, 0xc9,
	0xc6, 0xe8, 0x35, 0x2f, 0x68, 0x6b, 0x7b, 0xde, 0xe0, 0x0b, 0xd6, 0x4d, 0x6b, 0xcc, 0x6e, 0xcf,
	0xf2, 0x77, 0x7a, 0xec, 0xab, 0x0e, 0xa0, 0x73, 0x15, 0x2b, 0x39, 0xd1, 0x46, 0xd2, 0xbe, 0xe8,
	0x00, 0xa2, 0x37, 0x98, 0x66, 0xed, 0xc6, 0xe8, 0xae, 0xcb, 0x1c, 0x3c, 0x52, 0x0b, 0xc3, 0xb5,
	0xed, 0xe1, 0xe2, 0x5e, 0x75, 0xfb, 0x23, 0x45, 0x21, 0xa9, 0x52, 0x76, 0xbc, 0x8f, 0x4f, 0x32,
	0x7a, 0x82, 0xd9, 0xd9, 0x1f, 0xf8, 0x7f, 0xd1, 0xcb, 0x74, 0xfb, 0x5c, 0x32, 0x5d, 0x99, 0x5d,
	0x92, 0x8b, 0x3a, 0xad, 0x59, 0x69, 0xe8, 0xbe, 0x29, 0xf9, 0x07, 0x95, 0x92, 0x32, 0x49, 0xd2,
	0xb2, 0x3b, 0x83, 0xbc, 0x22, 0x8c, 0xa7, 0xf6, 0x34, 0x76, 0x9e, 0x7d, 0xbc, 0xfe, 0x04, 0x00,
	0x00, 0xff, 0xff, 0x50, 0xb9, 0x54, 0x99, 0x36, 0x02, 0x00, 0x00,
}
